version: '3.1'
services:
    postgres:
        image: postgres:latest
        container_name: financeapp-postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
volumes:
    .postgres:
